This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./Beatty_DSS_Essay.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Beatty_DSS_Essay.acn....done (12 entries accepted, 0 rejected).
Sorting entries....done (52 comparisons).
Generating output file Beatty_DSS_Essay.acr....done (19 lines written, 0 warnings).
Output written in Beatty_DSS_Essay.acr.
Transcript written in Beatty_DSS_Essay.alg.
