This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./Adam_Literature_Review_Essay.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Adam_Literature_Review_Essay.acn....done (31 entries accepted, 0 rejected).
Sorting entries....done (203 comparisons).
Generating output file Adam_Literature_Review_Essay.acr....done (43 lines written, 0 warnings).
Output written in Adam_Literature_Review_Essay.acr.
Transcript written in Adam_Literature_Review_Essay.alg.
