This is makeindex, version 2.16 [MiKTeX 25.4].
Scanning style file ./Adam_Thesis_Proposal.ist...........................done (27 attributes redefined, 0 ignored).
Scanning input file Adam_Thesis_Proposal.acn....done (36 entries accepted, 0 rejected).
Sorting entries....done (200 comparisons).
Generating output file Adam_Thesis_Proposal.acr....done (48 lines written, 0 warnings).
Output written in Adam_Thesis_Proposal.acr.
Transcript written in Adam_Thesis_Proposal.alg.
